source("./read_data.R")
source("./bagofwords.R")
post   <- JH_word_of_bag_POST(combined_timelines)
during <- JH_word_of_bag_DURING(combined_timelines)
pre    <- JH_word_of_bag_PRE(combined_timelines)
names(pre) <- c("rank", "PRE\n\nMALE TOP WORDS", "PRE\n\nMALE COUNT", "PRE\n\nFEMALE TOP WORDS", "PRE\n\nFEMALE COUNT")
names(during) <- c("rank", "DURING\n\nMALE TOP WORDS", "DURING\n\nMALE COUNT", "DURING\n\nFEMALE TOP WORDS", "DURING\n\nFEMALE COUNT")
names(post) <- c("rank", "POST\n\nMALE TOP WORDS", "POST\n\nMALE COUNT", "POST\n\nFEMALE TOP WORDS", "POST\n\nFEMALE COUNT")
View(pre)
View(during[,-1])
View(post)
View(cbind(pre, during[,-1], post[,-1]))
