source("./read_data.R")
source("./bagofwords.R")
data.person <- combined_timelines %>% filter(PERSON_FLAG == "1", abs(tweet_time_lag) < 20)
post   <- JH_word_of_bag_POST(data.person)
during <- JH_word_of_bag_DURING(data.person)
pre    <- JH_word_of_bag_PRE(data.person)
names(pre) <- c("rank", "PRE\n\nMALE TOP WORDS", "PRE\n\nMALE COUNT", "PRE\n\nFEMALE TOP WORDS", "PRE\n\nFEMALE COUNT")
names(during) <- c("rank", "DURING\n\nMALE TOP WORDS", "DURING\n\nMALE COUNT", "DURING\n\nFEMALE TOP WORDS", "DURING\n\nFEMALE COUNT")
names(post) <- c("rank", "POST\n\nMALE TOP WORDS", "POST\n\nMALE COUNT", "POST\n\nFEMALE TOP WORDS", "POST\n\nFEMALE COUNT")
# View(pre)
# View(during[,-1])
# View(post)
# View(cbind(pre, during[,-1], post[,-1]))
print(cbind(pre, during[,-1], post[,-1]))
